import fs from 'node:fs';
import path from 'node:path';
import PDFDocument from 'pdfkit';
import dayjs from 'dayjs';
import { env } from '../config/env';
import { ParsedDocument } from '../lib/document-types';

const logoPath = path.resolve(process.cwd(), '../flywheels/assets/branding/flywheels-logo.png');

export async function buildDocumentPdf(documentData: ParsedDocument & { documentNumber: string }) {
  const pdf = new PDFDocument({ margin: 40, size: 'A4' });
  const chunks: Buffer[] = [];

  pdf.on('data', (chunk) => chunks.push(chunk as Buffer));

  pdf.font('Helvetica-Bold').fontSize(18);
  if (fs.existsSync(logoPath)) {
    pdf.image(logoPath, 40, 32, { width: 72 });
  }

  pdf.text(env.PDF_COMPANY_NAME, 130, 40);
  pdf.font('Helvetica').fontSize(10);
  pdf.text(env.PDF_COMPANY_ADDRESS, 130, 64);
  pdf.text(`${env.PDF_COMPANY_PHONE} | ${env.PDF_COMPANY_EMAIL}`, 130, 78);
  if (env.PDF_GST) {
    pdf.text(`GST: ${env.PDF_GST}`, 130, 92);
  }

  pdf.moveTo(40, 120).lineTo(555, 120).strokeColor('#FF0000').lineWidth(2).stroke();

  pdf.fillColor('#000000').font('Helvetica-Bold').fontSize(16);
  pdf.text(documentData.type.toUpperCase(), 40, 140);
  pdf.fontSize(11).font('Helvetica');
  pdf.text(`Number: ${documentData.documentNumber}`, 40, 168);
  pdf.text(`Date: ${dayjs().format('DD MMM YYYY, hh:mm A')}`, 40, 184);

  pdf.text(`Customer: ${documentData.customerName}`, 320, 168, { align: 'left' });
  pdf.text(`Vehicle: ${documentData.vehicleNumber}`, 320, 184, { align: 'left' });
  pdf.text(`Model: ${documentData.carModel}`, 320, 200, { align: 'left' });

  const tableTop = 240;
  pdf.font('Helvetica-Bold');
  pdf.text('Description', 40, tableTop);
  pdf.text('Qty', 360, tableTop, { width: 40, align: 'right' });
  pdf.text('Rate', 410, tableTop, { width: 60, align: 'right' });
  pdf.text('Amount', 480, tableTop, { width: 70, align: 'right' });
  pdf.moveTo(40, tableTop + 18).lineTo(555, tableTop + 18).strokeColor('#000000').lineWidth(1).stroke();

  let currentTop = tableTop + 30;
  pdf.font('Helvetica');
  for (const item of documentData.items) {
    pdf.text(item.description, 40, currentTop, { width: 300 });
    pdf.text(item.quantity.toFixed(0), 360, currentTop, { width: 40, align: 'right' });
    pdf.text(item.unitPrice.toFixed(2), 410, currentTop, { width: 60, align: 'right' });
    pdf.text(item.total.toFixed(2), 480, currentTop, { width: 70, align: 'right' });
    currentTop += 24;
  }

  pdf.moveTo(340, currentTop + 12).lineTo(555, currentTop + 12).strokeColor('#D1D5DB').stroke();
  pdf.font('Helvetica-Bold');
  pdf.text('Subtotal', 380, currentTop + 24, { width: 80, align: 'right' });
  pdf.text(documentData.subtotal.toFixed(2), 480, currentTop + 24, { width: 70, align: 'right' });
  pdf.text('Total', 380, currentTop + 48, { width: 80, align: 'right' });
  pdf.fillColor('#FF0000').text(documentData.total.toFixed(2), 480, currentTop + 48, { width: 70, align: 'right' });
  pdf.fillColor('#000000');

  pdf.font('Helvetica').fontSize(10);
  pdf.text('Generated by FLYWHEELS AUTO', 40, 760, { align: 'center', width: 515 });

  pdf.end();

  return await new Promise<Buffer>((resolve) => {
    pdf.on('end', () => resolve(Buffer.concat(chunks)));
  });
}

